// Package replication is the transactor's push-based replication hub: it
// broadcasts WAL records, seal/root markers and per-connection responses to
// subscribed replicas through a single ordered output queue.  Port of
// eavt_transactor_nim/replication.nim.
package replication

import (
	"encoding/binary"
	"net"
	"sync"

	"eavt-go/internal/msgpack"
)

// BacklogMaxBytes caps a subscriber's pending bytes (fail-stop above it).
const BacklogMaxBytes = 64 * 1024 * 1024

// WalFrame builds {"ev":"wal","data":<bin>}.
func WalFrame(data []byte) []byte {
	return msgpack.Marshal(msgpack.Map{
		{Key: msgpack.Str("ev"), Value: msgpack.Str("wal")},
		{Key: msgpack.Str("data"), Value: msgpack.Bin(data)},
	})
}

// SealFrame builds {"ev":"seal","idx":idx}.
func SealFrame(idx int) []byte {
	return msgpack.Marshal(msgpack.Map{
		{Key: msgpack.Str("ev"), Value: msgpack.Str("seal")},
		{Key: msgpack.Str("idx"), Value: msgpack.Int(int64(idx))},
	})
}

// RootFrame builds {"ev":"root","name":name,"maxT":maxT}.
func RootFrame(name string, maxT int64) []byte {
	return msgpack.Marshal(msgpack.Map{
		{Key: msgpack.Str("ev"), Value: msgpack.Str("root")},
		{Key: msgpack.Str("name"), Value: msgpack.Str(name)},
		{Key: msgpack.Str("maxT"), Value: msgpack.Int(maxT)},
	})
}

// SnapshotFrame builds the initial snapshot frame.
func SnapshotFrame(sealed []string, openTail []byte, root, blobDir string) []byte {
	arr := make(msgpack.Array, len(sealed))
	for i, p := range sealed {
		arr[i] = msgpack.Str(p)
	}
	return msgpack.Marshal(msgpack.Map{
		{Key: msgpack.Str("ev"), Value: msgpack.Str("snapshot")},
		{Key: msgpack.Str("sealed"), Value: arr},
		{Key: msgpack.Str("openTail"), Value: msgpack.Bin(openTail)},
		{Key: msgpack.Str("root"), Value: msgpack.Str(root)},
		{Key: msgpack.Str("blobDir"), Value: msgpack.Str(blobDir)},
	})
}

// Subscriber is one replication connection.
type Subscriber struct {
	conn net.Conn
	hub  *Hub

	mu       sync.Mutex
	buf      []byte
	queue    [][]byte
	backlog  int64
	draining bool
	closed   bool
}

// Conn returns the underlying connection.
func (s *Subscriber) Conn() net.Conn { return s.conn }

// Closed reports whether the subscriber was torn down.
func (s *Subscriber) Closed() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.closed
}

func (s *Subscriber) flushBufLocked() {
	if len(s.buf) > 0 {
		s.queue = append(s.queue, WalFrame(s.buf))
		s.buf = nil
	}
}

// EnqueueResponse queues a response frame (flushing pending WAL first so the
// records generated by the request precede its response).
func (s *Subscriber) EnqueueResponse(body []byte) {
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return
	}
	s.flushBufLocked()
	s.queue = append(s.queue, body)
	s.backlog += int64(4 + len(body))
	s.mu.Unlock()
	s.pump()
}

func (s *Subscriber) appendWal(data []byte) {
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return
	}
	s.buf = append(s.buf, data...)
	s.backlog += int64(len(data))
	over := s.backlog > BacklogMaxBytes
	s.mu.Unlock()
	if over {
		s.markClosed()
	}
}

func (s *Subscriber) markClosed() {
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return
	}
	s.closed = true
	conn := s.conn
	s.mu.Unlock()
	if conn != nil {
		_ = conn.Close()
	}
	if s.hub != nil {
		s.hub.Remove(s)
	}
}

func (s *Subscriber) pump() {
	s.mu.Lock()
	if s.draining || s.closed || s.conn == nil {
		s.mu.Unlock()
		return
	}
	s.draining = true
	s.mu.Unlock()
	go s.drain()
}

func (s *Subscriber) drain() {
	for {
		s.mu.Lock()
		if s.closed || len(s.queue) == 0 {
			s.draining = false
			s.mu.Unlock()
			return
		}
		body := s.queue[0]
		s.queue = s.queue[1:]
		s.mu.Unlock()
		if err := writeFrame(s.conn, body); err != nil {
			s.markClosed()
			return
		}
		// Credit the frame that just left the queue (4-byte header + body),
		// so backlog tracks PENDING bytes — not the cumulative total.  The
		// Nim subscriber does the same in sendFrame; without it a fast
		// writer trips BacklogMaxBytes after 64 MiB of total traffic and the
		// subscriber is closed for no reason.
		s.mu.Lock()
		s.backlog -= int64(4 + len(body))
		if s.backlog < 0 {
			s.backlog = 0
		}
		s.mu.Unlock()
	}
}

func writeFrame(conn net.Conn, body []byte) error {
	hdr := make([]byte, 4)
	binary.BigEndian.PutUint32(hdr, uint32(len(body)))
	if _, err := conn.Write(hdr); err != nil {
		return err
	}
	if len(body) > 0 {
		_, err := conn.Write(body)
		return err
	}
	return nil
}

// Hub fans out events to all subscribers.
type Hub struct {
	mu      sync.Mutex
	subs    []*Subscriber
	BlobDir string
}

// NewHub creates a hub.
func NewHub(blobDir string) *Hub { return &Hub{BlobDir: blobDir} }

// Register adds a subscriber for a connection.
func (h *Hub) Register(conn net.Conn) *Subscriber {
	s := &Subscriber{conn: conn, hub: h}
	h.mu.Lock()
	h.subs = append(h.subs, s)
	h.mu.Unlock()
	return s
}

// Remove drops a subscriber.
func (h *Hub) Remove(s *Subscriber) {
	h.mu.Lock()
	for i, x := range h.subs {
		if x == s {
			h.subs = append(h.subs[:i], h.subs[i+1:]...)
			break
		}
	}
	h.mu.Unlock()
}

// Find returns the subscriber for a connection, if any.
func (h *Hub) Find(conn net.Conn) *Subscriber {
	h.mu.Lock()
	defer h.mu.Unlock()
	for _, s := range h.subs {
		if s.conn == conn && !s.Closed() {
			return s
		}
	}
	return nil
}

// BroadcastWal forwards WAL record bytes to every subscriber (memcpy only).
func (h *Hub) BroadcastWal(data []byte) {
	h.mu.Lock()
	subs := append([]*Subscriber(nil), h.subs...)
	h.mu.Unlock()
	for _, s := range subs {
		s.appendWal(data)
	}
}

// BroadcastSeal forwards a segment-seal marker.
func (h *Hub) BroadcastSeal(idx int) {
	h.mu.Lock()
	subs := append([]*Subscriber(nil), h.subs...)
	h.mu.Unlock()
	for _, s := range subs {
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			continue
		}
		s.flushBufLocked()
		s.queue = append(s.queue, SealFrame(idx))
		s.backlog += 48
		s.mu.Unlock()
		s.pump()
	}
}

// BroadcastRoot forwards a published root.
func (h *Hub) BroadcastRoot(name string, maxT int64) {
	h.mu.Lock()
	subs := append([]*Subscriber(nil), h.subs...)
	h.mu.Unlock()
	for _, s := range subs {
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			continue
		}
		s.flushBufLocked()
		s.queue = append(s.queue, RootFrame(name, maxT))
		s.backlog += 64
		s.mu.Unlock()
		s.pump()
	}
}

// SendSnapshot sends the full initial snapshot to a subscriber.
func (h *Hub) SendSnapshot(s *Subscriber, sealed []string, openTail []byte, root string) {
	s.EnqueueResponse(SnapshotFrame(sealed, openTail, root, h.BlobDir))
}
