[workspace]
members = ["eavt-cli", "eavt-server", "spier-blobstore-memory", "spier-blobstore-file", "spier-blobstore-s3", "spier-journal-file", "spier-memtable", "spier-kvstore", "spier-storage-traits", "spier-value", "spier-transactor", "spier-transactor-py", "spier-datalog", "spier-eavt-query", "spier-eavt-query-py", "spier-sql-parse", "spier-sql-parse-py", "spier-sql-frontend", "spier-planner", "spier-compiler", "spier-query-ir"]
default-members = ["eavt-cli", "eavt-server", "spier-blobstore-memory", "spier-blobstore-file", "spier-blobstore-s3", "spier-journal-file", "spier-memtable", "spier-kvstore", "spier-storage-traits", "spier-value", "spier-transactor", "spier-transactor-py", "spier-datalog", "spier-eavt-query", "spier-eavt-query-py", "spier-sql-parse", "spier-sql-parse-py", "spier-sql-frontend", "spier-planner", "spier-compiler", "spier-query-ir"]
resolver = "2"
