[workspace]
members = ["eavt-cli", "eavt-server", "spier-kvstore", "spier-storage-traits", "spier-value", "spier-transactor", "spier-datalog", "spier-eavt-query", "spier-eavt-query-py", "spier-sql-parse", "spier-sql-parse-py", "spier-sql-frontend", "spier-planner", "spier-compiler", "spier-query-ir", "spier-scheme", "spier-page-store-nim"]
default-members = ["eavt-cli", "eavt-server", "spier-kvstore", "spier-storage-traits", "spier-value", "spier-transactor", "spier-datalog", "spier-eavt-query", "spier-eavt-query-py", "spier-sql-parse", "spier-sql-parse-py", "spier-sql-frontend", "spier-planner", "spier-compiler", "spier-query-ir", "spier-scheme", "spier-page-store-nim"]
resolver = "2"
