[package]
name = "spier-transactor"
version = "0.1.0"
edition = "2021"
description = "EAVT engine (uses spier-kvstore for KV operations)"

[dependencies]
spier-kvstore = { path = "../spier-kvstore" }
spier-storage-traits = { path = "../spier-storage-traits" }
spier-value = { path = "../spier-value" }
