[package]
name = "spier-eavt-query"
version = "0.1.0"
edition = "2021"
description = "EAVT query engine (SQL compiler + VM)"

[lib]
crate-type = ["rlib"]

[dependencies]
chrono = "0.4"
spier-compiler = { path = "../spier-compiler" }
spier-datalog = { path = "../spier-datalog" }
spier-query-ir = { path = "../spier-query-ir" }
spier-sql-frontend = { path = "../spier-sql-frontend" }
spier-sql-parse = { path = "../spier-sql-parse" }
spier-storage-traits = { path = "../spier-storage-traits" }
spier-transactor = { path = "../spier-transactor" }
spier-value = { path = "../spier-value" }
