[package]
name = "spier-compiler"
version = "0.1.0"
edition = "2021"
description = "SQL compiler (SQL → VMProgram)"

[dependencies]
spier-datalog = { path = "../spier-datalog" }
spier-planner = { path = "../spier-planner" }
spier-query-ir = { path = "../spier-query-ir" }
spier-sql-parse = { path = "../spier-sql-parse" }
spier-value = { path = "../spier-value" }
