# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eavt_client import eavt_pb2 as eavt__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eavt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EavtServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sql = channel.unary_stream(
                '/eavt.EavtService/Sql',
                request_serializer=eavt__pb2.SqlRequest.SerializeToString,
                response_deserializer=eavt__pb2.SqlRow.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/eavt.EavtService/Execute',
                request_serializer=eavt__pb2.SqlRequest.SerializeToString,
                response_deserializer=eavt__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/eavt.EavtService/Status',
                request_serializer=eavt__pb2.StatusRequest.SerializeToString,
                response_deserializer=eavt__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Tree = channel.unary_unary(
                '/eavt.EavtService/Tree',
                request_serializer=eavt__pb2.TreeRequest.SerializeToString,
                response_deserializer=eavt__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.Dump = channel.unary_stream(
                '/eavt.EavtService/Dump',
                request_serializer=eavt__pb2.DumpRequest.SerializeToString,
                response_deserializer=eavt__pb2.DatomRow.FromString,
                _registered_method=True)
        self.Memtable = channel.unary_unary(
                '/eavt.EavtService/Memtable',
                request_serializer=eavt__pb2.MemtableRequest.SerializeToString,
                response_deserializer=eavt__pb2.MemtableResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/eavt.EavtService/Flush',
                request_serializer=eavt__pb2.FlushRequest.SerializeToString,
                response_deserializer=eavt__pb2.FlushResponse.FromString,
                _registered_method=True)


class EavtServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Sql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Memtable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EavtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sql': grpc.unary_stream_rpc_method_handler(
                    servicer.Sql,
                    request_deserializer=eavt__pb2.SqlRequest.FromString,
                    response_serializer=eavt__pb2.SqlRow.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=eavt__pb2.SqlRequest.FromString,
                    response_serializer=eavt__pb2.ExecuteResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=eavt__pb2.StatusRequest.FromString,
                    response_serializer=eavt__pb2.StatusResponse.SerializeToString,
            ),
            'Tree': grpc.unary_unary_rpc_method_handler(
                    servicer.Tree,
                    request_deserializer=eavt__pb2.TreeRequest.FromString,
                    response_serializer=eavt__pb2.TreeResponse.SerializeToString,
            ),
            'Dump': grpc.unary_stream_rpc_method_handler(
                    servicer.Dump,
                    request_deserializer=eavt__pb2.DumpRequest.FromString,
                    response_serializer=eavt__pb2.DatomRow.SerializeToString,
            ),
            'Memtable': grpc.unary_unary_rpc_method_handler(
                    servicer.Memtable,
                    request_deserializer=eavt__pb2.MemtableRequest.FromString,
                    response_serializer=eavt__pb2.MemtableResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=eavt__pb2.FlushRequest.FromString,
                    response_serializer=eavt__pb2.FlushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eavt.EavtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eavt.EavtService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EavtService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eavt.EavtService/Sql',
            eavt__pb2.SqlRequest.SerializeToString,
            eavt__pb2.SqlRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eavt.EavtService/Execute',
            eavt__pb2.SqlRequest.SerializeToString,
            eavt__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eavt.EavtService/Status',
            eavt__pb2.StatusRequest.SerializeToString,
            eavt__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eavt.EavtService/Tree',
            eavt__pb2.TreeRequest.SerializeToString,
            eavt__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eavt.EavtService/Dump',
            eavt__pb2.DumpRequest.SerializeToString,
            eavt__pb2.DatomRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Memtable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eavt.EavtService/Memtable',
            eavt__pb2.MemtableRequest.SerializeToString,
            eavt__pb2.MemtableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eavt.EavtService/Flush',
            eavt__pb2.FlushRequest.SerializeToString,
            eavt__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
