## connection.nim — Data server per-connection handling (chronos).
##
## One event loop serves every connection.  Requests are dispatched
## pipelined: each frame is spawned as an independent async handler so
## that long-running streams yield between batches while the read loop
## continues accepting new frames.  Response frames carry the request's
## correlation id so the query server can demultiplex them on a single shared
## connection that also carries the replication event stream.
##
## Replication ("replicate") is handled inline: the server registers a
## subscriber and sends the snapshot (direct write, outside the queue —
## never counted against the backlog).  After that, EVERY frame to that
## transport — events AND responses — flows through the subscriber's single
## output queue (enqueueResponse): the WAL records generated by a request
## are enqueued by the sink during execution, before the response, so the
## replica's reader applies them before the ack completes (read-your-writes).
## Connections without a "replicate" subscription write responses directly.

import std/[options, strutils, monotimes, streams, tables]
import chronos
import msgpack4nim
import scheme, msgpack_scan
import stats
import engine, eavt, kvstore
import kvstore_async
import shared_engine
import protocol
import replication
import logutil
import wire
import hostfns
import edn_tx

proc writeFrameAsync(transp: StreamTransport; body: string) {.async.} =
  var buf = newSeq[byte](4 + body.len)
  buf[0] = byte(body.len shr 24); buf[1] = byte(body.len shr 16)
  buf[2] = byte(body.len shr 8); buf[3] = byte(body.len)
  if body.len > 0:
    copyMem(addr buf[4], addr body[0], body.len)
  discard await transp.write(buf)

proc writeFrameQueued(eng: SharedEngine; transp: StreamTransport;
                      body: string) {.async.} =
  ## Despacho de saída por transporte: conexão com subscrição de replicação
  ## → fila única do subscriber (ordem wal-antes-de-response estrutural);
  ## conexão direta (sem replicate) → escrita direta, como antes.
  let sub = eng.hub.find(transp)
  if sub != nil and not sub.closed:
    sub.enqueueResponse(body)
  else:
    await transp.writeFrameAsync(body)

proc writeResponseAsync(eng: SharedEngine; transp: StreamTransport;
                        columns: seq[string];
                        rows: seq[seq[SExpr]]; more: bool;
                        error: string = ""; id: string = "") {.async.} =
  var ms = MsgStream.init(256)
  var fieldCount = 1  # "more"
  if id.len > 0: inc fieldCount
  if error.len > 0:
    inc fieldCount  # "error"
  else:
    fieldCount += 2  # "columns" + "rows"
  ms.pack_map(fieldCount)
  if id.len > 0:
    ms.pack("id"); ms.pack(id)
  if error.len > 0:
    ms.pack("error"); ms.pack(error)
    ms.pack("more"); ms.pack(false)
  else:
    ms.pack("columns")
    ms.pack_array(columns.len)
    for c in columns: ms.pack(c)
    ms.pack("rows")
    ms.pack_array(rows.len)
    for row in rows:
      ms.pack_array(row.len)
      for v in row:
        writeSExprPlain(ms, v)
    ms.pack("more"); ms.pack(more)
  await eng.writeFrameQueued(transp, ms.data)

proc writeErrorAsync(eng: SharedEngine; transp: StreamTransport; msg: string;
                     id: string = "") {.async.} =
  await writeResponseAsync(eng, transp, @[], @[], false, msg, id)

proc nextBatchSafe(sess: StreamingSession; maxRows: int): (seq[seq[SExpr]], bool) {.
    raises: [ValueError].} =
  try:
    sess.nextBatch(maxRows)
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc executeProgramSafe(session: QuerySession): SExpr {.raises: [ValueError].} =
  try:
    executeProgram(session)
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc allocateTxSafe(eng: SharedEngine): int64 {.raises: [ValueError].} =
  try:
    eng.store.eavt.allocateTAndWriteTx()
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc transactTxSafe(ops: EngineOps; txops: seq[TxWOp]): edn_tx.TxReport {.
    raises: [ValueError].} =
  try:
    transactTx(ops, txops)
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc buildStatsSafe(eng: SharedEngine): stats.CompileStats {.raises: [ValueError].} =
  try:
    eng.store.eavt.buildCompileStats()
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc scanDatomsSafe(eng: SharedEngine; cf: int): seq[eavt.Datom] {.
    raises: [ValueError].} =
  try:
    var res: seq[eavt.Datom]
    for d in eng.store.eavt.scanDatoms(cf):
      res.add(d)
    res
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc kvPutSafe(eng: SharedEngine; cf: int; key, val: seq[byte]) {.
    raises: [ValueError].} =
  try:
    eng.kv.putKv(cf, key, val)
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc kvDeleteSafe(eng: SharedEngine; cf: int; key: seq[byte]) {.
    raises: [ValueError].} =
  try:
    eng.kv.deleteKv(cf, key)
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc kvGetSafe(eng: SharedEngine; cf: int; key: seq[byte]): Option[seq[byte]] {.
    raises: [ValueError].} =
  try:
    eng.kv.getKv(cf, key)
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc kvScanPairsSafe(eng: SharedEngine; cf: int): seq[(seq[byte], seq[byte])] {.
    raises: [ValueError].} =
  try:
    var res: seq[(seq[byte], seq[byte])]
    let mc = eng.kv.openScanCursorKv(cf)
    while true:
      let kvp = mc.nextKv()
      if kvp.isNone: break
      res.add(kvp.get)
    res
  except Exception as e:
    raise (ref ValueError)(msg: e.msg)

proc execScheme(eng: SharedEngine; req: Request; transp: StreamTransport) {.async.} =
  let program = SchemeProgram(body: req.program)
  if req.mode != "query" and req.mode != "exec":
    await eng.writeErrorAsync(transp, "unknown scheme mode: " & req.mode, req.id)
    return
  let tx = if req.mode == "exec": allocateTxSafe(eng) else: 1'i64
  if req.mode == "query":
    let proto = newQuerySession(eng.store, program, req.params, tx, none[int64]())
    let sess = newStreamingSession(proto)
    while true:
      let (rows, more) = nextBatchSafe(sess, 100)
      await writeResponseAsync(eng, transp, @[], rows, more, id = req.id)
      if not more: break
  else:
    let session = newQuerySession(eng.store, program, req.params, tx, none[int64]())
    let tExec = getMonoTime().ticks
    let r = executeProgramSafe(session)
    eng.store.execWallNs += getMonoTime().ticks - tExec
    inc eng.store.execCount
    eng.store.printSavePerf()
    eng.store.resetSaveCounters()
    eng.store.eavt.printSpPerf()
    eng.store.eavt.resetSpCounters()
    eng.store.kv.printBwPerf()
    eng.store.kv.resetBwCounters()
    eng.store.decodeNs = 0
    eng.store.decodeCount = 0
    if r.kind == sList and r.items.len >= 2 and r.items[0].kind == sSymbol and
       r.items[0].symval == "result":
      await writeResponseAsync(eng, transp, @[], @[r.items[1..^1]], false, id = req.id)
    else:
      await writeResponseAsync(eng, transp, @[], @[], false,
                                "unexpected result: " & $r, req.id)

proc execTx(eng: SharedEngine; req: Request; transp: StreamTransport) {.async.} =
  ## Native EDN transaction (docs/tx-protocol.md §3): interpret the op
  ## vectors against the engine, reply with a tx-report
  ## {tempids: {...}, tx: t} or an error frame.
  logDebug("tx", "execTx: enter, ops=" & $req.txdata.len)
  let txReport = transactTxSafe(eng.store, req.txdata)
  logDebug("tx", "execTx: report ready, tempids=" & $txReport.tempids.len)
  var ms = MsgStream.init(256)
  var fieldCount = 3  # tempids + tx + more
  if req.id.len > 0: inc fieldCount
  ms.pack_map(fieldCount)
  if req.id.len > 0:
    ms.pack("id"); ms.pack(req.id)
  ms.pack("tempids")
  ms.pack_map(int64(txReport.tempids.len))
  for tid, eid in pairs(txReport.tempids):
    ms.pack(tid)      # tempids are negative int64 keys (§5.1)
    ms.pack(eid)
  ms.pack("tx"); ms.pack(txReport.tx)
  ms.pack("more"); ms.pack(false)
  # CRITICAL: via the single output queue — WAL bytes for this tx are flushed
  # before the response reaches the client (same contract as scheme exec;
  # docs/scheme-transport.md and AGENTS.md "fila única de saída").
  logDebug("tx", "execTx: writing report frame, " & $ms.data.len & " bytes")
  await writeFrameQueued(eng, transp, ms.data)
  logDebug("tx", "execTx: report frame written")

proc handleSchema(eng: SharedEngine; id: string;
                  transp: StreamTransport) {.async.} =
  let cstats = buildStatsSafe(eng)
  var ms = MsgStream.init(256)
  var fieldCount = 2  # "schema" + "more"
  if id.len > 0: inc fieldCount
  ms.pack_map(fieldCount)
  if id.len > 0:
    ms.pack("id"); ms.pack(id)
  ms.pack("schema")
  packStats(ms, cstats)
  ms.pack("more"); ms.pack(false)
  await eng.writeFrameQueued(transp, ms.data)

proc handleAdmin(eng: SharedEngine; command: string; id: string;
                 transp: StreamTransport) {.async.} =
  proc gcReportText(rep: seq[byte]): string =
    if rep.len < 41: return "gc: no report"
    proc u64le(rep: seq[byte]; off: int): uint64 =
      for i in 0..7: result = result or (uint64(rep[off + i]) shl uint64(8 * i))
    "roots_scanned=" & $u64le(rep, 0) & " roots_removed=" & $u64le(rep, 8) &
      " blobs_scanned=" & $u64le(rep, 16) & " blobs_removed=" & $u64le(rep, 24) &
      " live_blobs=" & $u64le(rep, 32) & " dry_run=" & $rep[40]
  if command.startsWith("dump"):
    let parts = command.splitWhitespace()
    let index = if parts.len >= 2: parts[1].toUpperAscii() else: "EAVT"
    let cf = case index
      of "AEVT": 1
      of "AVET": 2
      of "VAET": 3
      else: 0
    var rows: seq[seq[SExpr]]
    let datoms = scanDatomsSafe(eng, cf)
    for datom in datoms:
      if datom.retracted: continue
      rows.add(@[
        SExpr(kind: sInt, ival: datom.e),
        SExpr(kind: sStr, sval: datom.attrName & "(" & $datom.a & ")"),
        datom.value,
        SExpr(kind: sInt, ival: datom.t),
      ])
      if rows.len >= 100:
        await writeResponseAsync(eng, transp, @["e", "attr", "value", "t"], rows,
                                  true, id = id)
        rows.setLen(0)
    await writeResponseAsync(eng, transp, @["e", "attr", "value", "t"], rows,
                              false, id = id)
  else:
    let output = case command
      of "flush":
        if eng.kv.readOnly:
          "error: read-only"
        else:
          let fut = eng.flusher.requestFlushAsync()
          fut.callback = proc(udata: pointer) {.gcsafe, raises: [].} = discard
          "ok: flush requested"
      of "flush-sync":
        if eng.kv.readOnly:
          "error: read-only"
        else:
          await eng.flusher.requestFlushAsync()
          "ok: flushed"
      of "gc", "gc-dry":
        if eng.kv.readOnly:
          "error: read-only"
        else:
          await eng.flusher.requestGcAsync(command == "gc-dry")
          gcReportText(eng.flusher.lastGcReport)
      of "status":
        "memtable: " & $eng.kv.memtableSize() & " bytes"
      of "memtable":
        $eng.kv.memtableSize()
      else:
        "unknown admin command: " & command
    var ms = MsgStream.init(128)
    var fieldCount = 2  # "output" + "more"
    if id.len > 0: inc fieldCount
    ms.pack_map(fieldCount)
    if id.len > 0:
      ms.pack("id"); ms.pack(id)
    ms.pack("output"); ms.pack(output)
    ms.pack("more"); ms.pack(false)
    await eng.writeFrameQueued(transp, ms.data)

proc handleKv(eng: SharedEngine; req: Request; transp: StreamTransport) {.async.} =
  case req.kvOp
  of "put":
    kvPutSafe(eng, req.kvCf, req.kvKey, req.kvValue)
    await writeResponseAsync(eng, transp, @[], @[], false, id = req.id)
  of "get":
    let val = kvGetSafe(eng, req.kvCf, req.kvKey)
    if val.isSome:
      await writeResponseAsync(eng, transp, @[], @[@[SExpr(kind: sBytes, bytesval: val.get)]],
                                false, id = req.id)
    else:
      await writeResponseAsync(eng, transp, @[], @[], false, id = req.id)
  of "scan":
    let pairs = kvScanPairsSafe(eng, req.kvCf)
    var rows: seq[seq[SExpr]]
    for (key, value) in pairs:
      rows.add(@[
        SExpr(kind: sBytes, bytesval: key),
        SExpr(kind: sBytes, bytesval: value),
      ])
      if rows.len >= 100:
        await writeResponseAsync(eng, transp, @["key", "value"], rows, true, id = req.id)
        rows.setLen(0)
    await writeResponseAsync(eng, transp, @["key", "value"], rows, false, id = req.id)
  of "delete":
    kvDeleteSafe(eng, req.kvCf, req.kvKey)
    await writeResponseAsync(eng, transp, @[], @[], false, id = req.id)
  else:
    await writeResponseAsync(eng, transp, @[], @[], false,
                              "unknown kv op: " & req.kvOp, req.id)

# ── Pipelined request dispatch ──────────────────────────────────────────────

proc processFrame(eng: SharedEngine; raw: string; id: string;
                  transp: StreamTransport) {.async: (raises: []).} =
  ## Parse one request frame and dispatch to the appropriate handler.
  ## Errors are written back as response frames (tagged with the request's
  ## correlation id) — nothing escapes this proc.
  try:
    let tDecode = getMonoTime().ticks
    var req = parseRequest(raw, eng.store.symtab)
    eng.store.decodeNs += getMonoTime().ticks - tDecode
    inc eng.store.decodeCount
    req.id = id  # id from the outer frame header (already parsed)
    case req.kind
    of rkScheme: await execScheme(eng, req, transp)
    of rkTx: await execTx(eng, req, transp)
    of rkSchema: await handleSchema(eng, req.id, transp)
    of rkAdmin: await handleAdmin(eng, req.command, req.id, transp)
    of rkKv: await handleKv(eng, req, transp)
  except CatchableError as e:
    try:
      await eng.writeErrorAsync(transp, e.msg, id)
    except CatchableError as e2:
      # Expected: client already gone when the error frame is written.
      logDebug("transactor", "error frame delivery failed (" & excMsg(e2) &
        "); original error: " & excMsg(e))

# ── Main connection loop ────────────────────────────────────────────────────

proc serveConnection*(eng: SharedEngine; transp: StreamTransport) {.
    async: (raises: []).} =
  var isReplication = false
  while true:
    var hdr: array[4, byte]
    try:
      await transp.readExactly(addr hdr[0], 4)
    except CatchableError:
      break  # client disconnected
    let len = int(hdr[0]) shl 24 or int(hdr[1]) shl 16 or
              int(hdr[2]) shl 8 or int(hdr[3])
    if len <= 0 or len > 100_000_000:
      break
    let raw = newString(len)
    if len > 0:
      try:
        await transp.readExactly(addr raw[0], len)
      except CatchableError:
        break

    # Replication subscription: capture the open WAL tail, register the
    # subscriber and send the snapshot as a DIRECT write (never queued —
    # it does not count against the backlog and cannot trigger the stall
    # discard).  From here on, every frame to this transport — wal/seal/root
    # events AND request responses — flows through the subscriber's single
    # output queue: request N's wal records are enqueued by the sink during
    # execution, before N's response, so the replica applies them before
    # the ack.  register() before capturing the tail means records broadcast
    # between the two land in BOTH the snapshot's openTail and the
    # subscriber buf — re-applied on the replica as idempotent puts.
    if not isReplication:
      if getTopStr(raw, "type") == "replicate":
        isReplication = true
        var sub = Subscriber(transp: transp)
        eng.hub.register(sub)
        try:
          let sealed = collectSnapshot(eng.kv.path, eng.kv.ps[].currentRoot)
          var tail: seq[byte] = @[]
          if eng.walw != nil:
            tail = eng.walw.buf
          let rootName = eng.kv.ps[].currentRoot
          await sub.sendSnapshot(sealed, tail, rootName, eng.kv.path)
          # Flush any wal bytes enqueued while the snapshot was in flight.
          sub.pump()
        except CatchableError as e:
          logDebug("transactor", "replication snapshot failed (" & excMsg(e) &
            "); subscriber removed")
          sub.closed = true
          eng.hub.remove(sub)
        continue  # back to read loop (pipelined)

    # Correlation id via top-level key scan — no full frame parse here;
    # processFrame decodes what it needs.
    let id = getTopStr(raw, "id")
    asyncSpawn processFrame(eng, raw, id, transp)
