## replication.nim — Push-based replication hub for the transactor.
##
## The server registers its WAL sink, seal and root publish hooks through
## the replication hub.  Connected replicas receive:
##
##   1. snapshot: sealed segment paths (immutable files on the shared fs) +
##      open-tail bytes (the volatile in-memory WAL buffer) + root + blob dir
##   2. wal : immediate forward of every journal record (the sink callback,
##             under kv.lock — only memcpy here, socket writes are async)
##   3. seal: segment rotation (live treap → pending; fresh live takes over)
##   4. root: flush published — load new root, discard pending treap
##
## Protocol: length-prefixed msgpack frames (same framing as client protocol),
## one-way server → replica, keyed by "ev" field.
##
## SINGLE OUTPUT QUEUE: every frame written to a replication transport
## (wal/seal/root events AND response frames for requests pipelined on that
## connection) flows through one Subscriber queue.  Ordering is structural,
## not a per-call-site discipline: a handler executes (broadcastWal memcpy's
## its records into s.buf) BEFORE enqueuing its response, and enqueueResponse
## flushes buf into the queue first — so the WAL records generated by a
## request always precede that request's response on the wire.  The replica's
## reader applies them in order: read-your-writes without any guard sleeps.

import std/[os, strutils, algorithm, streams]
import msgpack4nim
import chronos
import wire
import logutil

# ── Subscriber ──────────────────────────────────────────────────────────────

const ReplicationBacklogMaxBytes* = 64 * 1024 * 1024

type
  EvKind* = enum evWal, evSeal, evRoot, evResponse

  Ev = object
    case kind: EvKind
    of evWal: data: seq[byte]
    of evSeal: idx: int
    of evRoot: name: string
    of evResponse: body: string

  ReplicationHub* = ref object
    subscribers*: seq[Subscriber]
    blobDir: string

  Subscriber* = ref object
    transp*: StreamTransport
    hub: ptr ReplicationHub
    ## Um único caminho de saída por transporte de replicação: bytes wal
    ## quentes acumulam em `buf` (append do sink, um memcpy); ao ENFILEIRAR
    ## um marcador (seal/root) ou uma response, o buf pendente é descarregado
    ## na fila ANTES — um frame wal nunca atravessa uma fronteira de geração
    ## nem chega depois da response da request que o gerou. As três filas
    ## paralelas antigas drenavam buf-primeiro invertendo essa fronteira
    ## quando escritas pós-captura entravam antes do tick (réplica selava
    ## pós-seal junto com pré-seal; o root descartava a diferença → perda
    ## intermitente de db.*).
    buf: seq[byte]
    queue: seq[Ev]
    backlogBytes*: int64
    draining: bool
    closed*: bool

proc flushBuf(s: Subscriber) =
  ## Descarrega wal pendente como evento ANTES do marcador/response seguinte.
  if s.buf.len > 0:
    s.queue.add Ev(kind: evWal, data: s.buf)
    s.buf = @[]

proc pendingCount*(s: Subscriber): int =
  ## Total de frames pendentes (buf + fila) — observabilidade/testes.
  result = s.queue.len
  if s.buf.len > 0: inc result

proc sendFrame(s: Subscriber; body: string) {.async.} =
  if s.closed: return
  var frame = newSeq[byte](4 + body.len)
  frame[0] = byte(body.len shr 24); frame[1] = byte(body.len shr 16)
  frame[2] = byte(body.len shr 8); frame[3] = byte(body.len)
  if body.len > 0:
    copyMem(addr frame[4], unsafeAddr body[0], body.len)
  try:
    discard await s.transp.write(frame)
    s.backlogBytes -= int64(frame.len)
    if s.backlogBytes < 0: s.backlogBytes = 0
  except CatchableError:
    s.closed = true

proc sendEvent(s: Subscriber; body: string) {.async.} =
  await s.sendFrame(body)

# ── Frame builders (puros — testáveis sem socket) ───────────────────────────

proc walFrame*(data: seq[byte]): string =
  var ms = MsgStream.init(64 + data.len)
  ms.pack_map(2)
  ms.pack("ev"); ms.pack("wal")
  ms.pack("data")
  ms.pack_bin(data.len)
  if data.len > 0:
    var tmp = newString(data.len)
    copyMem(addr tmp[0], unsafeAddr data[0], data.len)
    appendRaw(ms, tmp)
  ms.data

proc sealFrame*(idx: int): string =
  var ms = MsgStream.init(32)
  ms.pack_map(2)
  ms.pack("ev"); ms.pack("seal")
  ms.pack("idx"); ms.pack(idx)
  ms.data

proc rootFrame*(name: string): string =
  var ms = MsgStream.init(64)
  ms.pack_map(2)
  ms.pack("ev"); ms.pack("root")
  ms.pack("name"); ms.pack(name)
  ms.data

## Monta os frames SAÍDA na ordem exata da fila — sem tocar socket.
proc collectOutgoing*(s: Subscriber): seq[string] =
  ## Eventos wal CONSECUTIVOS agregam-se num único frame (como no formato
  ## antigo); o marcador seal/root sempre fecha o frame corrente — uma
  ## fronteira de geração nunca é atravessada por bytes de outra geração.
  result = @[]
  var i = 0
  while i < s.queue.len:
    let ev = s.queue[i]
    inc i
    case ev.kind
    of evWal:
      var data = ev.data
      while i < s.queue.len and s.queue[i].kind == evWal:
        data.add s.queue[i].data
        inc i
      if data.len > 0:
        result.add walFrame(data)
    of evSeal:
      result.add sealFrame(ev.idx)
    of evRoot:
      result.add rootFrame(ev.name)
    of evResponse:
      result.add ev.body
  s.queue.setLen(0)

# ── Snapshot construction ───────────────────────────────────────────────────

proc collectSnapshot*(dir: string; rootName: string): seq[string] =
  ## List sealed journal segment paths (numerically sorted).
  let jdir = dir / "journal"
  var segs: seq[tuple[idx: int, path: string]] = @[]
  if dirExists(jdir):
    for kind, name in walkDir(jdir):
      let base = lastPathPart(name)
      if kind == pcFile and base.startsWith("journal."):
        try:
          segs.add((parseInt(base[8..^1]), name))
        except ValueError:
          # Non-numeric entry in journal dir — filter, not an error.
          logDebug("replication", "skipping non-segment file " & base)
  segs.sort(proc(a, b: tuple[idx: int, path: string]): int = cmp(a.idx, b.idx))
  for s in segs: result.add(s.path)

proc sendSnapshot*(s: Subscriber; sealed: seq[string]; openSeg: seq[byte];
                   rootName: string; blobDir: string) {.async.} =
  ## Send the full initial snapshot. Sealed segments are listed by path
  ## (immutable files on the shared filesystem — the replica reads them
  ## directly). The open-tail bytes (current in-memory WAL buffer, volatile)
  ## go in the frame. The replica reconstructs: PageStore trees from
  ## rootName + replays sealed segments into its pending treap + replays
  ## openTail into its live treap.
  var ms = MsgStream.init(256 + openSeg.len)
  ms.pack_map(5)
  ms.pack("ev"); ms.pack("snapshot")
  ms.pack("sealed")
  ms.pack_array(sealed.len)
  for p in sealed: ms.pack(p)
  ms.pack("openTail")
  # Encode as msgpack bin (raw bytes) instead of JSON int array
  ms.pack_bin(openSeg.len)
  if openSeg.len > 0:
    var tmp = newString(openSeg.len)
    copyMem(addr tmp[0], unsafeAddr openSeg[0], openSeg.len)
    appendRaw(ms, tmp)
  ms.pack("root"); ms.pack(rootName)
  ms.pack("blobDir"); ms.pack(blobDir)
  await s.sendEvent(ms.data)

# ── Replication hub ──────────────────────────────────────────────────────────

proc initReplicationHub*(blobDir: string): ReplicationHub =
  result = ReplicationHub(blobDir: blobDir)

proc register*(hub: ReplicationHub; s: Subscriber) =
  s.hub = cast[ptr ReplicationHub](hub)
  hub.subscribers.add(s)

proc remove*(hub: ReplicationHub; s: Subscriber) =
  let idx = hub.subscribers.find(s)
  if idx >= 0: hub.subscribers.delete(idx)

proc find*(hub: ReplicationHub; transp: StreamTransport): Subscriber =
  ## Subscriber de um transporte (ou nil). Usado pelo despacho de resposta:
  ## conexão com replicação → fila única; sem → escrita direta.
  for s in hub.subscribers:
    if s.transp == transp and not s.closed: return s

# ── Drain (single-flight, sem polling) ──────────────────────────────────────

proc drainTask(s: Subscriber) {.async.} =
  ## Único escritor do transporte de replicação: envia os frames enfileirados
  ## em ordem FIFO até a fila esvaziar ou o subscriber fechar. Acordado por
  ## enqueueResponse/broadcastSeal/broadcastRoot (pump) — sem tick, sem loop
  ## permanente.
  try:
    while not s.closed and (s.buf.len > 0 or s.queue.len > 0):
      s.flushBuf()
      for body in s.collectOutgoing():
        if s.closed: return
        await s.sendFrame(body)
  except CatchableError as e:
    # Expected: replica socket closed mid-drain.
    logDebug("replication", "subscriber drain ended (" & excMsg(e) & ")")
    s.closed = true
  finally:
    s.draining = false
    if s.closed and s.hub != nil:
      s.hub[].remove(s)

proc pump*(s: Subscriber) =
  ## Agenda um drain single-flight se não houver um em curso.
  if s.draining or s.closed or s.transp == nil: return
  s.draining = true
  asyncSpawn drainTask(s)

proc enqueueResponse*(s: Subscriber; body: string) =
  ## Enfileira uma frame de response no transporte de replicação.
  ## INVARIANTE: flushBuf garante que os bytes wal gerados pela request que
  ## produz esta response precedem a response no fio (ordem estrutural —
  ## o sink roda durante a execução, antes do enqueue).
  if s.closed: return
  s.flushBuf()
  s.queue.add Ev(kind: evResponse, body: body)
  s.backlogBytes += int64(4 + body.len)
  s.pump()

proc pruneClosed(hub: ptr ReplicationHub) =
  ## Descarta subscribers fechados (socket morto ou estagnado descartado).
  ## Executado fora de qualquer iteração de envio — single-threaded loop.
  var i = 0
  while i < hub.subscribers.len:
    if hub.subscribers[i].closed: hub.subscribers.delete(i)
    else: inc i

proc closeStalled(s: Subscriber) =
  ## Backlog acima do limite: o subscriber não acompanha a réplica — não
  ## serve na prática. Fecha o transporte (fail-stop): o query server
  ## reconecta em 1s e recebe snapshot novo. Nunca memória sem limite.
  ## logError: replication-relevante (AGENTS.md — log + fail-fast).
  logError("replication", "backlog " & $(s.backlogBytes shr 20) &
    " MiB acima do limite — fechando subscriber estagnado")
  s.closed = true
  if s.transp != nil:
    # closeWait é raises:[] em chronos — sem caminho de erro a reportar.
    asyncSpawn s.transp.closeWait()

proc broadcastWal*(hub: ptr ReplicationHub; p: ptr byte; len: int) =
  ## Called under kv.lock on the loop thread (journal sink).  Uma única
  ## cópia (para o buffer do subscriber) direto da view do w.buf.
  ## O sink não pode esperar (gcsafe, raises:[]) — a proteção contra
  ## consumer travado é descartar o subscriber acima da cota.
  if hub == nil or hub.subscribers.len == 0 or len <= 0: return
  pruneClosed(hub)
  for s in hub.subscribers.items:
    if s.closed: continue
    let old = s.buf.len
    s.buf.setLen(old + len)
    copyMem(addr s.buf[old], p, len)
    s.backlogBytes += int64(len)
    if s.backlogBytes > ReplicationBacklogMaxBytes:
      closeStalled(s)

proc broadcastSeal*(hub: ptr ReplicationHub; segIdx: int) =
  if hub == nil or hub.subscribers.len == 0: return
  pruneClosed(hub)
  for s in hub.subscribers.items:
    if not s.closed:
      s.flushBuf()
      s.queue.add Ev(kind: evSeal, idx: segIdx)
      s.backlogBytes += 48  # marcador — aproximação, geração é rara
      s.pump()

proc broadcastRoot*(hub: ptr ReplicationHub; rootName: string) =
  if hub == nil or hub.subscribers.len == 0: return
  pruneClosed(hub)
  for s in hub.subscribers.items:
    if not s.closed:
      s.flushBuf()
      s.queue.add Ev(kind: evRoot, name: rootName)
      s.backlogBytes += 64  # marcador — aproximação
      s.pump()
