package datalog

import (
	"os"
	"path/filepath"
	"testing"

	"eavt-go/internal/msgpack"
	S "eavt-go/internal/sexpr"
)

// TestGoldenVectors compares the Go compiler's wire output byte-for-byte
// against the 25 vectors generated by tools/dump_wire.nim (the same vectors
// the OCaml port validated).
func TestGoldenVectors(t *testing.T) {
	dir := filepath.Join("..", "..", "testdata", "golden", "query")
	ok := 0
	for i := 1; i <= 25; i++ {
		n := twoDigits(i)
		query, err := os.ReadFile(filepath.Join(dir, "q"+n+".q"))
		if err != nil {
			t.Fatalf("read q%s: %v", n, err)
		}
		want, err := os.ReadFile(filepath.Join(dir, "w"+n+".wire"))
		if err != nil {
			t.Fatalf("read w%s: %v", n, err)
		}
		statsBytes, err := os.ReadFile(filepath.Join(dir, "s"+n+".stats"))
		if err != nil {
			t.Fatalf("read s%s: %v", n, err)
		}
		sv, err := msgpack.Unmarshal(statsBytes)
		if err != nil {
			t.Fatalf("decode stats s%s: %v", n, err)
		}
		stats := DecodeCompileStats(sv)

		prog, _, _, _, err := CompileDatalogQueryDebug(string(query), stats)
		if err != nil {
			t.Errorf("q%s: compile error: %v", n, err)
			continue
		}
		got := S.ToWire(prog)
		if string(got) != string(want) {
			t.Errorf("q%s: wire mismatch (got %d bytes, want %d)", n, len(got), len(want))
			_ = os.WriteFile(filepath.Join(dir, "q"+n+".got"), got, 0o644)
			continue
		}
		ok++
	}
	t.Logf("golden: %d/25 vetores byte-identicos", ok)
	if ok != 25 {
		t.Fatalf("golden: only %d/25 vectors matched", ok)
	}
}

func twoDigits(i int) string {
	if i < 10 {
		return "0" + string(rune('0'+i))
	}
	return string(rune('0'+i/10)) + string(rune('0'+i%10))
}

func TestCompileStatsRoundTrip(t *testing.T) {
	s := NewCompileStats()
	s.AttrIDs["person/name"] = 100
	s.IndexEstimates["EAVT:"] = 42
	s.IndexEstimates["AVET:100:"] = 7
	s.PartitionIDs["db.part/user"] = 4
	s.RefAttrs["person/employer"] = true
	s.IndexedAttrs["person/name"] = true
	got := DecodeCompileStats(msgpack.UnmarshalMust(EncodeCompileStats(s)))
	if got.AttrIDs["person/name"] != 100 || got.IndexEstimates["EAVT:"] != 42 ||
		got.PartitionIDs["db.part/user"] != 4 || !got.RefAttrs["person/employer"] ||
		!got.IndexedAttrs["person/name"] {
		t.Fatalf("roundtrip = %#v", got)
	}
}

// TestExplainGolden compares the Go EXPLAIN renderer byte-for-byte against
// vectors rendered by nim_compiler/explain.nim (see testdata/gen_explain.nim).
func TestExplainGolden(t *testing.T) {
	dir := filepath.Join("..", "..", "testdata", "golden")
	ok := 0
	for i := 1; i <= 25; i++ {
		n := twoDigits(i)
		query, err := os.ReadFile(filepath.Join(dir, "query", "q"+n+".q"))
		if err != nil {
			t.Fatal(err)
		}
		statsBytes, err := os.ReadFile(filepath.Join(dir, "query", "s"+n+".stats"))
		if err != nil {
			t.Fatal(err)
		}
		want, err := os.ReadFile(filepath.Join(dir, "explain", "e"+n+".txt"))
		if err != nil {
			t.Fatal(err)
		}
		sv, err := msgpack.Unmarshal(statsBytes)
		if err != nil {
			t.Fatal(err)
		}
		res, err := CompileDatalogQueryResult(string(query), DecodeCompileStats(sv))
		if err != nil {
			t.Errorf("q%s: compile error: %v", n, err)
			continue
		}
		got := RenderExplain(res)
		if string(got) != string(want) {
			t.Errorf("q%s: explain mismatch\n--- got ---\n%s\n--- want ---\n%s", n, got, want)
			continue
		}
		ok++
	}
	if ok != 25 {
		t.Fatalf("explain golden: only %d/25 matched", ok)
	}
}
